<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SovereignGrid.Core\SovereignGrid.Core.csproj" />
    <ProjectReference Include="..\SovereignGrid.Storage\SovereignGrid.Storage.csproj" />
    <ProjectReference Include="..\SovereignGrid.Plugins\SovereignGrid.Plugins.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
